name: Sync

on:
  schedule:
    - cron: '0 0,10 * * *'
  workflow_dispatch: {}
  push:
    branches:
      - master


jobs:

  sync:
    name: Sync repositories
    runs-on: self-hosted
    steps:

      - name: Set up Go 1.19.1
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
        id: go

      - uses: actions/checkout@v3
      - run: |
             git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

#      - uses: awalsh128/cache-apt-pkgs-action@latest
#        with:
#          packages: libxml2-utils jq
#          version: 1.0

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Sync terraform providers
        run: |
              sudo apt-get update
              sudo apt-get install -y libxml2-utils jq
              echo "BEFORE **** $GOPATH"
              cd schemas-extractor
              export GOPATH=~/go/
              # echo "After **** $GOPATH"
              export CHECK_SKIP="1"
              make
              cp -r schemas/* ../terraform/model/
              cp providers.list ../terraform/model

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: latest-sync
          path: terraform
          retention-days: 5

  commit-results:
    name: Commit results
    runs-on: ubuntu-latest
    needs: [sync]
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Fetch artifacts
        uses: actions/download-artifact@v1
        with:
          name: latest-sync

      - name: Apply latest artifact
        run: |
              sudo apt update
              git status
              rsync -a latest-sync/ terraform/
              rm -rf latest-sync
              git status

      - name: Set commit message
        id: commit
        run: echo "desc=Update metadata as of  $(date)" >> "$GITHUB_OUTPUT"

#      - uses: stefanzweifel/git-auto-commit-action@v4.0.0
#        with:
#          commit_message: ${{ steps.commit.outputs.desc }}
#          branch: sync
#          commit_user_name: Ash Jindal
#          commit_user_email: ajorpheus@users.noreply.github.com

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          pull: '--rebase --autostash'
          author_name: Ash Jindal
          author_email: ajorpheus@users.noreply.github.com
          message: ${{ steps.commit.outputs.desc }}

      - name: Merge sync changes to master
        run: |
              git status
              git checkout master
              if [ "$(git branch --list sync)" ]; then git cherry-pick sync && git push; fi
